# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gug/test

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gug/test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gug/test/CMakeFiles /home/gug/test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gug/test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named c

# Build rule for target.
c : cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c
.PHONY : c

# fast build rule for target.
c/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/build
.PHONY : c/fast

#=============================================================================
# Target rules for targets named qt

# Build rule for target.
qt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qt
.PHONY : qt

# fast build rule for target.
qt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/build
.PHONY : qt/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named test_c

# Build rule for target.
test_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_c
.PHONY : test_c

# fast build rule for target.
test_c/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_c.dir/build.make CMakeFiles/test_c.dir/build
.PHONY : test_c/fast

#=============================================================================
# Target rules for targets named algoritms_1

# Build rule for target.
algoritms_1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 algoritms_1
.PHONY : algoritms_1

# fast build rule for target.
algoritms_1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algoritms_1.dir/build.make CMakeFiles/algoritms_1.dir/build
.PHONY : algoritms_1/fast

#=============================================================================
# Target rules for targets named algoritms_2

# Build rule for target.
algoritms_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 algoritms_2
.PHONY : algoritms_2

# fast build rule for target.
algoritms_2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algoritms_2.dir/build.make CMakeFiles/algoritms_2.dir/build
.PHONY : algoritms_2/fast

algoritms_1.o: algoritms_1.c.o
.PHONY : algoritms_1.o

# target to build an object file
algoritms_1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algoritms_1.dir/build.make CMakeFiles/algoritms_1.dir/algoritms_1.c.o
.PHONY : algoritms_1.c.o

algoritms_1.i: algoritms_1.c.i
.PHONY : algoritms_1.i

# target to preprocess a source file
algoritms_1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algoritms_1.dir/build.make CMakeFiles/algoritms_1.dir/algoritms_1.c.i
.PHONY : algoritms_1.c.i

algoritms_1.s: algoritms_1.c.s
.PHONY : algoritms_1.s

# target to generate assembly for a file
algoritms_1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algoritms_1.dir/build.make CMakeFiles/algoritms_1.dir/algoritms_1.c.s
.PHONY : algoritms_1.c.s

algoritms_2.o: algoritms_2.cpp.o
.PHONY : algoritms_2.o

# target to build an object file
algoritms_2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algoritms_2.dir/build.make CMakeFiles/algoritms_2.dir/algoritms_2.cpp.o
.PHONY : algoritms_2.cpp.o

algoritms_2.i: algoritms_2.cpp.i
.PHONY : algoritms_2.i

# target to preprocess a source file
algoritms_2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algoritms_2.dir/build.make CMakeFiles/algoritms_2.dir/algoritms_2.cpp.i
.PHONY : algoritms_2.cpp.i

algoritms_2.s: algoritms_2.cpp.s
.PHONY : algoritms_2.s

# target to generate assembly for a file
algoritms_2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algoritms_2.dir/build.make CMakeFiles/algoritms_2.dir/algoritms_2.cpp.s
.PHONY : algoritms_2.cpp.s

c.o: c.cpp.o
.PHONY : c.o

# target to build an object file
c.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/c.cpp.o
.PHONY : c.cpp.o

c.i: c.cpp.i
.PHONY : c.i

# target to preprocess a source file
c.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/c.cpp.i
.PHONY : c.cpp.i

c.s: c.cpp.s
.PHONY : c.s

# target to generate assembly for a file
c.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c.dir/build.make CMakeFiles/c.dir/c.cpp.s
.PHONY : c.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

qt.o: qt.cpp.o
.PHONY : qt.o

# target to build an object file
qt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/qt.cpp.o
.PHONY : qt.cpp.o

qt.i: qt.cpp.i
.PHONY : qt.i

# target to preprocess a source file
qt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/qt.cpp.i
.PHONY : qt.cpp.i

qt.s: qt.cpp.s
.PHONY : qt.s

# target to generate assembly for a file
qt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qt.dir/build.make CMakeFiles/qt.dir/qt.cpp.s
.PHONY : qt.cpp.s

test_c.o: test_c.c.o
.PHONY : test_c.o

# target to build an object file
test_c.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_c.dir/build.make CMakeFiles/test_c.dir/test_c.c.o
.PHONY : test_c.c.o

test_c.i: test_c.c.i
.PHONY : test_c.i

# target to preprocess a source file
test_c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_c.dir/build.make CMakeFiles/test_c.dir/test_c.c.i
.PHONY : test_c.c.i

test_c.s: test_c.c.s
.PHONY : test_c.s

# target to generate assembly for a file
test_c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_c.dir/build.make CMakeFiles/test_c.dir/test_c.c.s
.PHONY : test_c.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... algoritms_1"
	@echo "... algoritms_2"
	@echo "... c"
	@echo "... main"
	@echo "... qt"
	@echo "... test_c"
	@echo "... algoritms_1.o"
	@echo "... algoritms_1.i"
	@echo "... algoritms_1.s"
	@echo "... algoritms_2.o"
	@echo "... algoritms_2.i"
	@echo "... algoritms_2.s"
	@echo "... c.o"
	@echo "... c.i"
	@echo "... c.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... qt.o"
	@echo "... qt.i"
	@echo "... qt.s"
	@echo "... test_c.o"
	@echo "... test_c.i"
	@echo "... test_c.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

