name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install deps
      run: |
        sudo apt-get install -y cmake libboost-all-dev
        pip install -r requirements.txt
        
    - name: Build
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build
    
    - name: Run tests
      run: |
        cd build && ctest --output-on-failure
        pytest tests/